server:
  port: 10002

spring:
  profiles:
    active: common-dev

  #ElasticSearch配置,自动配置类 ElasticsearchAutoConfiguration
  data:
    elasticsearch:
      repositories: true
      cluster-name: elasticsearch
      cluster-nodes: 192.168.0.178:9300
